name: osync
base: core18
version: git
summary: Tool to synchronize in a optimized way a lot of files to a FTP server.
description: |
  Osync is a Rust written tool designed to upload huge amount of files
  to a remote FTP server, in an efficient manner.
license: GPL-3.0

grade: stable
confinement: strict

parts:
  osync:
    plugin: rust
    source: .
    build-packages:
      - libc6-dev

apps:
  osync:
    command: bin/osync
    plugs:
      - home
      - removable-media
      - network